$(document).ready(function(){
    $("#opCliente").click(function(){
        $("#ulSubMenuCliente").slideDown(200);
    });
    $("#opCliente").dblclick(function(){
        $("#ulSubMenuCliente").slideUp(200);
    });
    $("#opUsuario").click(function(){
        $("#ulSubMenuUsuario").slideDown(200);
    });
    $("#opUsuario").dblclick(function(){
        $("#ulSubMenuUsuario").slideUp(200);
    });
    $("#opMenu").click(function(){
        $("#ulSubMenuMenu").slideDown(200);
    });
    $("#opMenu").dblclick(function(){
        $("#ulSubMenuMenu").slideUp(200);
    });
    $("#opPerfil").click(function(){
        $("#ulSubMenuPerfil").slideDown(200);
    });
    $("#opPerfil").dblclick(function(){
        $("#ulSubMenuPerfil").slideUp(200);
    });
    
    $(".btnOpenMenu").click(function(){
        $(".divDadosPerfil").fadeIn(200);
    });
    $(".btnCloseMenu").click(function(){
        $(".divDadosPerfil").fadeOut(200);
    });
});
$(window).resize(function(){
	if ($(window).width() >= 900){	
		$(".divDadosPerfil").fadeIn(0);
	}	
});